// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: report.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ReportService_GetSpendings_FullMethodName      = "/submodule.ReportService/GetSpendings"
	ReportService_GetIncomes_FullMethodName        = "/submodule.ReportService/GetIncomes"
	ReportService_BudgetPerformance_FullMethodName = "/submodule.ReportService/BudgetPerformance"
	ReportService_GoalProgress_FullMethodName      = "/submodule.ReportService/GoalProgress"
)

// ReportServiceClient is the client API for ReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReportServiceClient interface {
	GetSpendings(ctx context.Context, in *SpendingReq, opts ...grpc.CallOption) (*SpendingGet, error)
	GetIncomes(ctx context.Context, in *IncomeReq, opts ...grpc.CallOption) (*IncomeGet, error)
	BudgetPerformance(ctx context.Context, in *BudgetPerReq, opts ...grpc.CallOption) (*BudgetPerGet, error)
	GoalProgress(ctx context.Context, in *GoalProgresReq, opts ...grpc.CallOption) (*GoalProgresGet, error)
}

type reportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReportServiceClient(cc grpc.ClientConnInterface) ReportServiceClient {
	return &reportServiceClient{cc}
}

func (c *reportServiceClient) GetSpendings(ctx context.Context, in *SpendingReq, opts ...grpc.CallOption) (*SpendingGet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpendingGet)
	err := c.cc.Invoke(ctx, ReportService_GetSpendings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetIncomes(ctx context.Context, in *IncomeReq, opts ...grpc.CallOption) (*IncomeGet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncomeGet)
	err := c.cc.Invoke(ctx, ReportService_GetIncomes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) BudgetPerformance(ctx context.Context, in *BudgetPerReq, opts ...grpc.CallOption) (*BudgetPerGet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BudgetPerGet)
	err := c.cc.Invoke(ctx, ReportService_BudgetPerformance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GoalProgress(ctx context.Context, in *GoalProgresReq, opts ...grpc.CallOption) (*GoalProgresGet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoalProgresGet)
	err := c.cc.Invoke(ctx, ReportService_GoalProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportServiceServer is the server API for ReportService service.
// All implementations must embed UnimplementedReportServiceServer
// for forward compatibility
type ReportServiceServer interface {
	GetSpendings(context.Context, *SpendingReq) (*SpendingGet, error)
	GetIncomes(context.Context, *IncomeReq) (*IncomeGet, error)
	BudgetPerformance(context.Context, *BudgetPerReq) (*BudgetPerGet, error)
	GoalProgress(context.Context, *GoalProgresReq) (*GoalProgresGet, error)
	mustEmbedUnimplementedReportServiceServer()
}

// UnimplementedReportServiceServer must be embedded to have forward compatible implementations.
type UnimplementedReportServiceServer struct {
}

func (UnimplementedReportServiceServer) GetSpendings(context.Context, *SpendingReq) (*SpendingGet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpendings not implemented")
}
func (UnimplementedReportServiceServer) GetIncomes(context.Context, *IncomeReq) (*IncomeGet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIncomes not implemented")
}
func (UnimplementedReportServiceServer) BudgetPerformance(context.Context, *BudgetPerReq) (*BudgetPerGet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BudgetPerformance not implemented")
}
func (UnimplementedReportServiceServer) GoalProgress(context.Context, *GoalProgresReq) (*GoalProgresGet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoalProgress not implemented")
}
func (UnimplementedReportServiceServer) mustEmbedUnimplementedReportServiceServer() {}

// UnsafeReportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportServiceServer will
// result in compilation errors.
type UnsafeReportServiceServer interface {
	mustEmbedUnimplementedReportServiceServer()
}

func RegisterReportServiceServer(s grpc.ServiceRegistrar, srv ReportServiceServer) {
	s.RegisterService(&ReportService_ServiceDesc, srv)
}

func _ReportService_GetSpendings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpendingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetSpendings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_GetSpendings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetSpendings(ctx, req.(*SpendingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetIncomes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncomeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetIncomes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_GetIncomes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetIncomes(ctx, req.(*IncomeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_BudgetPerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BudgetPerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).BudgetPerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_BudgetPerformance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).BudgetPerformance(ctx, req.(*BudgetPerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GoalProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoalProgresReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GoalProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_GoalProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GoalProgress(ctx, req.(*GoalProgresReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ReportService_ServiceDesc is the grpc.ServiceDesc for ReportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "submodule.ReportService",
	HandlerType: (*ReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSpendings",
			Handler:    _ReportService_GetSpendings_Handler,
		},
		{
			MethodName: "GetIncomes",
			Handler:    _ReportService_GetIncomes_Handler,
		},
		{
			MethodName: "BudgetPerformance",
			Handler:    _ReportService_BudgetPerformance_Handler,
		},
		{
			MethodName: "GoalProgress",
			Handler:    _ReportService_GoalProgress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "report.proto",
}
